//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.20 at 10:57:51 PM IST 
//

@XmlSchema(namespace = "http://www.example.org/customer-details", elementFormDefault = XmlNsForm.QUALIFIED)
package org.example.customer_details;

import jakarta.xml.bind.annotation.XmlNsForm;
import jakarta.xml.bind.annotation.XmlSchema;
